### ISSUE TITLE
Shows "Hello World" and nothing useful in the Browser Extension tab

### ISSUE THREAD

**Issue by TSMMark** [ReactQuantum/ReactQuantum#39]
![screen shot 2019-01-29 at 5 38 15 pm](https://user-images.githubusercontent.com/4197823/51945470-d4259e80-23ec-11e9-888b-9730f1d36d09.png)

What is it supposed to do?

We're on React version 16.7.0

**Comment by alchi126** [comment]
Hi Mark,

Apologies for the confusion! We had a very early version on the master branch, but we've just updated. Please check it out again. 

Thanks,
Altai

**Comment by TSMMark** [comment]
Ok now I get the new layout with this logo in the tab

![image](https://user-images.githubusercontent.com/4197823/51948593-1227c000-23f7-11e9-920c-a452d3dd6319.png)

However I can only get it to say "PLEASE REFRESH PAGE", like it can't discover that React is mounted on the page. FTR I double checked that the React dev tools are still working properly and I am in development environment

**Comment by TSMMark** [comment]
Yeah, those were the steps I took. No problem, for now I will wait until the library is more stable — maybe when it is released to the Chrome web store. Thanks for your work

**Comment by TSMMark** [comment]
When going to remove the package I noticed these errors from the package, if that helps
 
<img width="647" alt="screen shot 2019-01-29 at 7 59 18 pm" src="https://user-images.githubusercontent.com/4197823/51950899-65524080-2400-11e9-8946-b8f1ddec238b.png">
